[package]
name = "did-webplus-wasm"
version = "0.1.0"
authors = [
    "Ben Nichols <ben.nichols@ledgerdomain.com>",
    "Victor Dods <victor.dods@ledgerdomain.com>",
]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

# Optimize for code size, not speed.  See https://rustwasm.github.io/book/reference/code-size.html
[profile.release]
# See https://github.com/rust-lang/rust/issues/72758 and https://doc.rust-lang.org/cargo/reference/profiles.html
lto = true
opt-level = 's'

[features]
# Define a wasm_bindgen "start" function that initializes the logger.  This is useful when you don't want
# to have to define the "start" function externally to this crate.
define-start-function = []

[dependencies]
anyhow = "1.0.94"
async-trait = "0.1.80"
console_error_panic_hook = "0.1.7"
did-key = { path = "../../did-key" }
did-webplus-cli-lib = { path = "../cli-lib", features = [
    "ed25519-dalek",
    "k256",
] }
did-webplus-core = { path = "../core", features = ["tracing"] }
did-webplus-doc-storage-mock = { path = "../doc-storage-mock" }
did-webplus-doc-store = { path = "../doc-store" }
did-webplus-jws = { path = "../jws", features = ["wasm-bindgen"] }
did-webplus-resolver = { path = "../resolver" }
did-webplus-software-wallet = { path = "../software-wallet" }
did-webplus-software-wallet-indexeddb = { path = "../software-wallet-indexeddb" }
did-webplus-wallet = { path = "../wallet" }
did-webplus-wallet-storage-mock = { path = "../wallet-storage-mock" }
js-sys = "0.3.76"
# TODO: Try to get rid of this, it's only used to initialize the logger using log::Level
log = "0.4.21"
selfhash = "0.4.0"
selfsign = { version = "0.6.0", features = [
    "ed25519-dalek",
    "k256",
    "wasm-bindgen",
] }
serde_json = "1.0.107"
serde_json_canonicalizer = "0.3.0"
storage-traits = { path = "../../storage-traits" }
time = { version = "0.3", features = ["wasm-bindgen"] }
tracing = { version = "0.1.37", features = ["log"] }
url = "2.5.0"
uuid = "1.9.1"
verifier-resolver = { path = "../../verifier-resolver" }
vjson-core = { path = "../../vjson/core" }
vjson-storage-mock = { path = "../../vjson/storage-mock" }
vjson-store = { path = "../../vjson/store" }
wasm-bindgen = "0.2.99"
wasm-bindgen-futures = "0.4.49"
wasm-logger = "0.2.0"

[dev-dependencies]
wasm-bindgen-test = "0.3.49"
