[package]
name = "did-webplus-vdr"
version = "0.1.0"
authors = [
    "Ben Nichols <ben.nichols@ledgerdomain.com>",
    "Victor Dods <victor.dods@ledgerdomain.com>",
]
edition = "2021"

[features]
postgres = ["did-webplus-vdr-lib/postgres"]
sqlite = ["did-webplus-vdr-lib/sqlite"]

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.4", features = ["derive", "env"] }
did-webplus-vdr-lib = { path = "../vdr-lib" }
dotenvy = "0.15.7"
tokio = { version = "1.41", features = ["full"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[dev-dependencies]
ctor = "0.4.1"
did-webplus-core = { path = "../core" }
did-webplus-mock = { path = "../mock" }
reqwest = "0.12.5"
test-util = { path = "../../test-util" }
tokio = { version = "1.41.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.37"
