[package]
name = "did-webplus-vdr"
version = "0.1.0"
authors = [
    "Ben Nichols <ben.nichols@ledgerdomain.com>",
    "Victor Dods <victor.dods@ledgerdomain.com>",
]
edition = "2021"

[dependencies]
anyhow = "1.0.94"
did-webplus-vdr-lib = { path = "../vdr-lib" }
tokio = { version = "1.41", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[dev-dependencies]
ctor = "0.2.8"
did-webplus-core = { path = "../core" }
did-webplus-mock = { path = "../mock" }
reqwest = "0.12.5"
tokio = { version = "1.41.0", features = ["macros", "rt-multi-thread"] }
