name: 'Build and Push to ECR'
description: 'Builds a docker image with advanced caching and pushes it to Amazon ECR'

inputs:
  module-name:
    description: "Name of the module to build. Used as the default image name and src dir unless 'image-name' or 'src-path' are used."
    required: true
  build-for-environment:
    description: "The backend environment we are building for (API calls are pointed to).  This should be one of (development, staging, production)."
    required: true
  extra-build-args:
    description: "Extra args passed to 'docker build'."
    required: false
  src-path:
    description: "What folder to be (generally to find the Dockerfile in) default is root of repo"
    required: false


runs:
  using: 'composite'
  steps:
    - uses: ./.github/actions/setup-env

    # Set up Docker Buildx - use remote BuildKit daemon for persistent cache
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: remote
        endpoint: tcp://buildkitd.infrastructure.svc.cluster.local:1234

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_REGION: us-west-2
      with:
        registries: "987071820073"

    - shell: bash
      env:
        AWS_REGION: us-west-2
      run: |
        # Env var parsing
        INPUT_SRC_PATH=${{ inputs.src-path }}
        IMAGE_NAME=${{ inputs.module-name }}
        SRC_PATH=${INPUT_SRC_PATH:-"./"}
        REPO_IMAGE=${{ steps.login-ecr.outputs.registry }}/$IMAGE_NAME
        ENVIRONMENT=${{ inputs.build-for-environment }}
        BRANCH_NAME=${{env.ENV_NAME}}
        IMAGE_TAG=$ENVIRONMENT-${{ env.SLUG }}
        CACHE_IMAGE=$REPO_IMAGE:buildcache

        # Create repo if needed
        aws ecr create-repository --repository-name $IMAGE_NAME || true

        # Go into folder
        cd $SRC_PATH

        # Generic args
        BUILD_ARGS="--build-arg BUILD_FOR_ENVIRONMENT=$ENVIRONMENT --build-arg IMAGE_TAG=$IMAGE_TAG"

        # Build with buildx using registry cache only
        echo "Building with cache from: $CACHE_IMAGE"
        docker buildx build \
          ${{ inputs.extra-build-args }} \
          $BUILD_ARGS \
          --cache-from type=registry,ref=$CACHE_IMAGE \
          --cache-to type=registry,ref=$CACHE_IMAGE,mode=max \
          --tag $REPO_IMAGE:$IMAGE_TAG \
          --tag $REPO_IMAGE:latest \
          --push \
          --provenance=false \
          .

        echo "Build complete! Tagged as $IMAGE_TAG and latest"